"""
Constants for VM Balancer
"""

# Migration settings
DEFAULT_MIGRATION_TIMEOUT = 1800  # 30 minutes
DEFAULT_MAX_MIGRATIONS_PER_CYCLE = 1
MIGRATION_HISTORY_RETENTION_HOURS = 1
MIGRATION_BLACKLIST_RETENTION_HOURS = 24

# Default thresholds
DEFAULT_CPU_OVERLOAD_THRESHOLD = 7.0
DEFAULT_MEMORY_OVERLOAD_THRESHOLD = 70.0
DEFAULT_CPU_TARGET_THRESHOLD = 6.0
DEFAULT_MEMORY_TARGET_THRESHOLD = 80.0

# SSH monitoring
DEFAULT_SSH_TIMEOUT = 10
DEFAULT_SSH_PORT = 22

# Balance intervals
DEFAULT_BALANCE_INTERVAL = 600  # 10 minutes

# VM density factor constants
VM_DENSITY_FACTOR_WEIGHT = 0.5
VM_DENSITY_FACTOR_CAP = 2.0
SSH_VM_DENSITY_FACTOR_WEIGHT = 0.3

# Logging
DEFAULT_LOG_LEVEL = "INFO"